# Generated by Django 6.0.3 on 2026-04-23 08:40

import forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0024_residencepermitfeedback_validity_in_months"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("board-games", "Board Games"),
                            ("cinemas", "Cinemas"),
                            ("dentists", "Dentists"),
                            ("doctors", "Doctors"),
                            ("driving-schools", "Driving Schools"),
                            ("foreign-ingredients", "Foreign Ingredients"),
                            ("gyms", "Gyms"),
                            ("gynecologists", "Gynecologists"),
                            ("hairdressers", "Hairdressers"),
                            ("lawyers", "Lawyers"),
                            ("motorcycle-stores", "Motorcycle Stores"),
                            ("pizza", "Pizza"),
                            ("psychiatrists", "Psychiatrists"),
                            ("psychotherapists", "Psychotherapists"),
                            ("relocation-agencies", "Relocation Agencies"),
                            ("steuerberater", "Steuerberater"),
                        ],
                        max_length=100,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("google_maps_id", models.CharField(blank=True, max_length=200)),
                ("languages", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_owner", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, validators=[forms.utils.validate_email])),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
