# Generated by Django 6.0.3 on 2026-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0025_placesuggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placesuggestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("board-games", "Board Games"),
                    ("cinemas", "Cinemas"),
                    ("dentists", "Dentists"),
                    ("doctors", "Doctors"),
                    ("driving-schools", "Driving Schools"),
                    ("foreign-ingredients", "Foreign Ingredients"),
                    ("gyms", "Gyms"),
                    ("gynecologists", "Gynecologists"),
                    ("hairdressers", "Hairdressers"),
                    ("lawyers", "Lawyers"),
                    ("motorcycle-stores", "Motorcycle Stores"),
                    ("pizza", "Pizza"),
                    ("psychiatrists", "Psychiatrists"),
                    ("psychotherapists", "Psychotherapists"),
                    ("relocation-agencies", "Relocation Agencies"),
                    ("steuerberater", "Steuerberater"),
                    ("veterinarians", "Veterinarians"),
                ],
                max_length=100,
            ),
        ),
    ]
