# Generated by Django 6.0.3 on 2026-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0026_alter_placesuggestion_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="placesuggestion",
            name="accepts_public_health_insurance",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
