# Generated by Django 6.0.6 on 2026-06-19 10:16

import forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0027_placesuggestion_accepts_public_health_insurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmigrationOfficeLawsuit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, validators=[forms.utils.validate_email])),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("BLUE_CARD", "Blue Card"),
                            ("CITIZENSHIP", "Citizenship"),
                            ("FAMILY_REUNION_VISA", "Family reunion visa"),
                            ("FREELANCE_VISA", "Freelance visa"),
                            ("JOB_SEEKER_VISA", "Job seeker visa"),
                            ("PERMANENT_RESIDENCE", "Permanent residence"),
                            ("STUDENT_VISA", "Student visa"),
                            ("WORK_VISA", "Work visa"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("application_date", models.DateField()),
                ("immigration_office_has_replied", models.BooleanField(default=None, null=True)),
                ("meets_requirements", models.BooleanField(default=None, null=True)),
                ("has_submitted_documents", models.BooleanField(default=None, null=True)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
