# Generated by Django 6.0.6 on 2026-06-19 12:29

import django.db.models.deletion
import django.utils.timezone
import forms.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0028_immigrationofficelawsuit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmigrationOfficeLawsuitCustomerNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Scheduled"), (1, "Error"), (2, "Sent"), (3, "Sent and redacted for privacy")],
                        default=0,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.immigrationofficelawsuit"
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImmigrationOfficeLawsuitFeedbackNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Scheduled"), (1, "Error"), (2, "Sent"), (3, "Sent and redacted for privacy")],
                        default=0,
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(default=functools.partial(forms.utils._offset_from_now, weeks=1)),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.immigrationofficelawsuit"
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImmigrationOfficeLawsuitLawyerNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Scheduled"), (1, "Error"), (2, "Sent"), (3, "Sent and redacted for privacy")],
                        default=0,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.immigrationofficelawsuit"
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
                "abstract": False,
            },
        ),
    ]
