# Generated by Django 6.0.6 on 2026-06-25 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0029_immigrationofficelawsuitcustomernotification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenshipFeedbackNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Scheduled"), (1, "Error"), (2, "Sent"), (3, "Sent and redacted for privacy")],
                        default=0,
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="forms.citizenshipfeedback",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResidencePermitFeedbackNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Scheduled"), (1, "Error"), (2, "Sent"), (3, "Sent and redacted for privacy")],
                        default=0,
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="forms.residencepermitfeedback",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
                "abstract": False,
            },
        ),
    ]
