# Generated by Django 6.0.6 on 2026-06-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0030_citizenshipfeedbacknotification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizenshipfeedbacknotification",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_notification",
                to="forms.citizenshipfeedback",
            ),
        ),
        migrations.AlterField(
            model_name="residencepermitfeedbacknotification",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_notification",
                to="forms.residencepermitfeedback",
            ),
        ),
    ]
