# Generated by Django 6.0.6 on 2026-08-08 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0032_citizenshiplawsuitnotification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="immigrationofficelawsuitlawyernotification",
            name="case",
        ),
        migrations.RemoveField(
            model_name="immigrationofficelawsuitfeedbacknotification",
            name="case",
        ),
        migrations.DeleteModel(
            name="ImmigrationOfficeLawsuitCustomerNotification",
        ),
        migrations.DeleteModel(
            name="ImmigrationOfficeLawsuitLawyerNotification",
        ),
        migrations.DeleteModel(
            name="ImmigrationOfficeLawsuit",
        ),
        migrations.DeleteModel(
            name="ImmigrationOfficeLawsuitFeedbackNotification",
        ),
    ]
