[env]
_.file = ".env"
COMPOSE_PROJECT_NAME = "allaboutberlin"
BUILDKIT_PROGRESS = "plain"

_.python.venv = { path = ".venv", create = true }

# = INSTALL=====================================================================

[tools]
uv = "latest"
ruff = "latest"
python = "3.13"
shellcheck = "latest"
pre-commit = "latest"
editorconfig-checker = "latest"

[tasks.setup]
description = "Install local dependencies to run the project"
silent = true
depends = ["update-hosts-file"]
run = """
uv pip install -r frontend/requirements.txt
uv pip install -r backend/requirements.txt
uv pip install -r requirements-dev.txt
playwright install --with-deps
mise generate git-pre-commit --hook=pre-commit --write --task=pre-commit
mise generate git-pre-commit --hook=pre-push --write --task=pre-push
"""

[tasks.update-hosts-file]
description = "Add services.localhost to /etc/hosts, so that https://services.localhost works"
run = """
if ! grep -q 'services.localhost' /etc/hosts; then
  echo "[$(date +'%H:%M:%S')] Adding 'services.localhost' to /etc/hosts (requires sudo)"
  echo '127.0.0.1 services.localhost' | sudo tee -a /etc/hosts > /dev/null
fi
"""

[hooks]
enter = { task = "setup" }

# = RUN ========================================================================

[tasks.site]
description = "Serve the frontend, reload on changes. Fast and resource-efficient."
run = """
ursus -wfs -c frontend/ursus_config.py
"""

[tasks.dev]
description = "Serve the frontend and the backend in docker."
usage = '''
flag "--bundle-js"
'''

quiet = true
run = """
JS_BUNDLING_IS="disabled"
if [ "${usage_bundle_js:-false}" = "true" ]; then
  export BUNDLE_JS=1
  JS_BUNDLING_IS="enabled"
fi

if ! docker info >/dev/null 2>&1; then
  echo "[$(date +'%H:%M:%S')] Starting docker daemon"
  open -a Docker;
fi

echo "[$(date +'%H:%M:%S')] Waiting for docker daemon to be ready"
while ! docker ps > /dev/null 2>&1; do
  sleep 1;
done

echo "[$(date +'%H:%M:%S')] Starting docker containers with JS bundling ${JS_BUNDLING_IS}"
compose_output=$(docker compose up --build -d --force-recreate 2>&1) || { echo "$compose_output"; exit 1; }

max_attempts=10
attempt=1
echo "[$(date +'%H:%M:%S')] Waiting for backend availability"
until curl --fail -s -k https://localhost/api/forms/ >/dev/null; do
  if [ "$attempt" -ge "$max_attempts" ]; then
    echo "[$(date +'%H:%M:%S')] Can't reach server after $max_attempts seconds."
    exit 1
  fi
  ((attempt++))
  sleep 1
done
"""

[tasks.wait-for-frontend]
quiet = true
usage = '''
flag "--bundle-js"
'''
depends = ["dev {% if usage.bundle_js %}--bundle-js{% endif %}"]
run = """
max_attempts=30
attempt=1
echo "[$(date +'%H:%M:%S')] Waiting for frontend availability"
until curl --fail -s -k https://localhost >/dev/null; do
  if [ "$attempt" -ge "$max_attempts" ]; then
    echo "[$(date +'%H:%M:%S')] Can't reach server after $max_attempts seconds."
    exit 1
  fi
  ((attempt++))
  sleep 1
done

echo "[$(date +'%H:%M:%S')] Waiting for frontend rebuild to finish"
until [ $(docker ps --filter "name=frontend" --filter "health=healthy" --quiet) ]; do
  sleep 1
done
"""

[tasks.import-db]
description = "Imports the latest backup of the production database"
run = """
TMP_DB=${TMPDIR:-/tmp}/api.db

scp "aab:/var/db-backups/$(date -I).db" "$TMP_DB"
docker compose cp "$TMP_DB" backend:/var/db/api.db
rm "$TMP_DB"
"""

# = WRITE ======================================================================

[tasks.make-title-image]
description = "Generate an entry image with a given title"
usage = '''
arg "<title>" help="Title text to render on the image"
arg "<output>" help="Output path for the PNG file"
'''
run = """
frontend/scripts/make_title_image.py "${usage_title}" "${usage_output}"
"""

[tasks.import-places]
description = "Fetch place suggestions from the API and add them to the places yaml files"
run = """
frontend/scripts/import_places.py
"""

[tasks.add-review]
description = "Add a review to a guide"
run = """
frontend/scripts/add_review.py
"""

# = TEST =======================================================================

[tasks.test-api]
quiet = true
depends = ["wait-for-frontend --bundle-js"]
run = """
echo "[$(date +'%H:%M:%S')] Running API tests..."
test_output=$(docker compose exec backend python3 manage.py test -b --verbosity 0 2>&1) || { echo "$test_output"; exit 1; }
"""

[tasks.test-ui]
quiet = true
depends = ["wait-for-frontend --bundle-js"]
run = """
echo "[$(date +'%H:%M:%S')] Running UI tests..."
pytest tests $@
"""

[tasks.fix-snapshots]
depends = ["test-ui"]
run = """
echo "[$(date +'%H:%M:%S')] Updating snapshots for UI tests..." \
pytest tests --lf --update-snapshots
"""

[tasks.test]
quiet = true
depends = ["test-api", "test-ui"]
run = """
echo "[$(date +'%H:%M:%S')] Finished running tests"
"""

# = CLEANUP ====================================================================

[tasks.shellcheck]
description = "Lint shell scripts with shellcheck"
quiet = true
run = """
for file in $(find . -type f -name "*.sh" -not -path '*/[@.]*'); do shellcheck $file; done;
"""

[tasks.lint]
description = "Run various linters for the project"
quiet = true
run = """
echo "[$(date +'%H:%M:%S')] Running shellcheck..."
mise shellcheck

echo "[$(date +'%H:%M:%S')] Running ruff..."
ruff check --quiet

echo "[$(date +'%H:%M:%S')] Running editorconfig-checker..."
ec

echo "[$(date +'%H:%M:%S')] Running ursus lint..."
ursus lint --level=ERROR -c frontend/ursus_config.py
"""

[tasks.format]
description = "Automatically format the code"
run = """
ruff format
"""

[tasks.pre-commit]
run = """
mise format
mise lint
"""

[tasks.pre-push]
run = """
mise lint
mise test
"""
