[templates.zusatzbeitrag]
extends = "default"
url = "https://www.krankenkassen.de/gesetzliche-krankenkassen/krankenkasse-beitrag/zusatzbeitrag/"
selector = "#content table"
prompt = """
Read this table. Return the latest Zusatzbeitrag for {insurer} as a percentage (in the leftmost column).
Return only the percentage, without rounding, without percent signs and without thousands separators. For decimal values, use a dot as the decimal mark.
If the value is not in this table, only return 'ERROR'.
"""

[monitors.zusatzbeitrag-aok]
extends = "zusatzbeitrag"
insurer = "AOK Nordost"
constant_to_update = "GKV_ZUSATZBEITRAG_AOK"

[monitors.zusatzbeitrag-barmer]
extends = "zusatzbeitrag"
insurer = "Barmer"
constant_to_update = "GKV_ZUSATZBEITRAG_BARMER"

[monitors.zusatzbeitrag-dak]
extends = "zusatzbeitrag"
insurer = "DAK-Gesundheit"
constant_to_update = "GKV_ZUSATZBEITRAG_DAK"

[monitors.zusatzbeitrag-hkk]
extends = "zusatzbeitrag"
insurer = "hkk"
constant_to_update = "GKV_ZUSATZBEITRAG_HKK"

[monitors.zusatzbeitrag-tk]
extends = "zusatzbeitrag"
insurer = "Techniker Krankenkasse"
constant_to_update = "GKV_ZUSATZBEITRAG_TK"

[monitors.zusatzbeitrag-average]
extends = "default"
url = "https://www.check24.de/gesetzliche-krankenversicherung/erhoehung-zusatzbeitraege/"
selector = "[component-export=InsuranceSummary]"
prompt = """
Read this page. Return the average (durchschnittliche) Zusatzbeitrag as a percentage.
Only return the number, without the %% sign. Use a dot as the decimal mark. Use no thousands separator.
If the value can't be found, only return 'ERROR'.
"""
constant_to_update = "GKV_AVG_ZUSATZBEITRAG"

[monitors.zusatzbeitrag-min]
extends = "zusatzbeitrag"
selector = ".a11y-table:first-of-type tr:first-of-type td:nth-child(2)"
prompt = """
Read this HTML text.
Only return the numeric value, without the %% sign. Use a dot as the decimal mark. Use no thousands separator.
If the value is not a percentage, only return 'ERROR'.
"""
constant_to_update = "GKV_MIN_ZUSATZBEITRAG"

[monitors.zusatzbeitrag-max]
extends = "zusatzbeitrag"
selector = ".a11y-table:first-of-type tr:last-of-type td:nth-child(2)"
prompt = """
Read this HTML text. Return the text value as a percentage, without rounding, without percent signs and without thousands separators. Use a dot as the decimal mark.
If the value is not a percentage, only return 'ERROR'.
"""
constant_to_update = "GKV_MAX_ZUSATZBEITRAG"

[monitors.pflegeversicherung-base-rate]
extends = "default"
url = "https://www.barmer.de/firmenkunden/sozialversicherung/beitraege/pflegeversicherung-beitraege-arbeitgeber"
selector = "table"
prompt = """
Read this table. Return the total Beitragssatz for a person with 1 child, as a percentage.
Return only the percentage, formatted as a float.
If the value is not in this table, only return 'ERROR'.
"""
constant_to_update = "PFLEGEVERSICHERUNG_BASE_RATE"