[templates.zusatzbeitrag]
extends = "default"
url = "https://www.krankenkassen.de/gesetzliche-krankenkassen/krankenkasse-beitrag/zusatzbeitrag/"
selector = "#content table"
prompt = """
Read this table. Return the latest Zusatzbeitrag for {insurer} as a percentage (in the leftmost column).
Return only the percentage, without percent signs or thousands separators. For decimal values, use a dot as the decimal mark.
If the value can't be found, only return 'ERROR'.
"""

[monitors.zusatzbeitrag-aok]
extends = "zusatzbeitrag"
insurer = "AOK Nordost"
constant_to_update = "GKV_ZUSATZBEITRAG_AOK"

[monitors.zusatzbeitrag-barmer]
extends = "zusatzbeitrag"
insurer = "Barmer"
constant_to_update = "GKV_ZUSATZBEITRAG_BARMER"

[monitors.zusatzbeitrag-dak]
extends = "zusatzbeitrag"
insurer = "DAK-Gesundheit"
constant_to_update = "GKV_ZUSATZBEITRAG_DAK"

[monitors.zusatzbeitrag-hkk]
extends = "zusatzbeitrag"
insurer = "hkk"
constant_to_update = "GKV_ZUSATZBEITRAG_HKK"

[monitors.zusatzbeitrag-tk]
extends = "zusatzbeitrag"
insurer = "Techniker Krankenkasse"
constant_to_update = "GKV_ZUSATZBEITRAG_TK"

[monitors.zusatzbeitrag-average]
extends = "default"
url = "https://www.check24.de/gesetzliche-krankenversicherung/erhoehung-zusatzbeitraege/"
selector = "[component-export=InsuranceSummary]"
prompt = """
Read this page. Return the average (durchschnittliche) Zusatzbeitrag as a percentage. Only return the number, without the %% sign. Use a dot as the decimal mark. Use no thousands separator. If the value can't be found, only return 'ERROR'.
"""
constant_to_update = "GKV_AVG_ZUSATZBEITRAG"

[monitors.zusatzbeitrag-max]
extends = "default"
url = "https://www.check24.de/gesetzliche-krankenversicherung/erhoehung-zusatzbeitraege/"
selector = ".w-full.border-collapse.max-w-4xl"
prompt = """
Read this text. Return the highest Zusatzbeitrag (in the rightmost column) among all listed providers, as a percentage. Only return the number, without the %% sign. Use a dot as the decimal mark. Use no thousands separator. If the value can't be found, only return 'ERROR'.
"""
constant_to_update = "GKV_MAX_ZUSATZBEITRAG"

[monitors.zusatzbeitrag-min]
extends = "default"
url = "https://www.check24.de/gesetzliche-krankenversicherung/erhoehung-zusatzbeitraege/"
selector = ".w-full.border-collapse.max-w-4xl"
prompt = """
Read this table. Return the lowest non-zero Zusatzbeitrag (in the leftmost column) among all "bundesweit" providers, as a percentage. Exclude "betriebsbezogen" and "regional" providers.
Only return the percentage, without percent signs or formatting. Use a dot as the decimal mark, but only if there are decimals. Use no thousands separator.
If the value can't be found, only return 'ERROR'.
"""
constant_to_update = "GKV_MIN_ZUSATZBEITRAG"
