# Generated by Django 6.1.1 on 2026-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="category",
            field=models.CharField(
                choices=[
                    ("housing", "Housing"),
                    ("work", "Work"),
                    ("immigration", "Immigration"),
                    ("living-in-germany", "Life in Germany"),
                    ("personal-finance", "Personal finance"),
                    ("family-friends-pets", "Family, friends, pets"),
                    ("health", "Health"),
                    ("where-to-find", "Where to find..."),
                    ("self-employment", "Self-employment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
