# Generated by Django 6.1.1 on 2026-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_alter_thread_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reply",
            name="removal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reply",
            name="removal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_banned", "User banned"),
                    ("deleted_by_moderator", "Deleted by moderator"),
                    ("deleted_by_user", "Deleted by user"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="modification_date",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="removal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="removal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_banned", "User banned"),
                    ("deleted_by_moderator", "Deleted by moderator"),
                    ("deleted_by_user", "Deleted by user"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
