# Generated by Django 6.0.3 on 2026-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0014_case_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="intent",
            field=models.CharField(
                choices=[
                    ("health", "Health insurance question"),
                    ("private", "Choose private health insurance"),
                    ("public", "Choose public health insurance"),
                    ("expat", "Choose expat health insurance"),
                    ("other", "Other/unknown"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
