# Generated by Django 6.0.6 on 2026-06-25 17:03

import forms.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0015_alter_case_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacknotification",
            name="delivery_date",
            field=models.DateTimeField(default=functools.partial(forms.utils._offset_from_now, days=5)),
        ),
    ]
