# Generated by Django 6.0.3 on 2026-08-17 12:47

import django_countries.fields
import forms.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0017_remove_case_broker"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthInsuranceSignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("referrer", models.CharField(blank=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("submitted", "Submitted to insurer"),
                            ("accepted", "Accepted by insurer"),
                            ("rejected", "Rejected by insurer"),
                            ("error", "Submission error"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("insurer", models.CharField(choices=[("tk", "Techniker Krankenkasse")], default="tk", max_length=10)),
                ("insurance_start_date", models.DateField()),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("azubi", "Azubi"),
                            ("studentEmployee", "Student (working)"),
                            ("studentSelfEmployed", "Student (self-employed)"),
                            ("studentUnemployed", "Student (unemployed)"),
                            ("selfEmployed", "Self-employed"),
                            ("unemployed", "Unemployed"),
                            ("other", "Other/unknown"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("unspecified", "Unspecified"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=15)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("birth_name", models.CharField(blank=True, max_length=150)),
                ("birth_date", models.DateField()),
                ("birth_place", models.CharField(max_length=50)),
                ("birth_country", django_countries.fields.CountryField(max_length=2)),
                ("nationality", django_countries.fields.CountryField(max_length=2)),
                ("email", models.EmailField(max_length=254, validators=[forms.utils.validate_email])),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "language",
                    models.CharField(choices=[("EN", "English"), ("DE", "German")], default="EN", max_length=2),
                ),
                ("street", models.CharField(max_length=150)),
                ("house_number", models.CharField(blank=True, max_length=30)),
                ("address_extra", models.CharField(blank=True, max_length=150)),
                ("postal_code", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=150)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("has_children", models.BooleanField()),
                ("insure_family_members", models.BooleanField(default=False)),
                ("receives_other_pension", models.BooleanField(default=False)),
                ("receives_public_pension", models.BooleanField(default=False)),
                ("is_exempt_from_social_contributions", models.BooleanField(default=False)),
                ("has_lived_abroad", models.BooleanField()),
                (
                    "country_of_last_insurance",
                    django_countries.fields.CountryField(blank=True, max_length=2, null=True),
                ),
                ("current_insurer_name", models.CharField(blank=True, max_length=25)),
                (
                    "current_insurance_type",
                    models.CharField(
                        blank=True, choices=[("public", "Public/statutory"), ("private", "Private")], max_length=15
                    ),
                ),
                ("is_currently_pflichtversichert", models.BooleanField(blank=True, null=True)),
                ("is_currently_policy_holder", models.BooleanField(blank=True, null=True)),
                ("is_salary_above_threshold", models.BooleanField()),
                ("is_first_job_in_germany", models.BooleanField()),
                ("employment_start_date", models.DateField()),
                ("employment_hours_per_week", models.PositiveIntegerField(blank=True, null=True)),
                ("employment_income_per_month", models.PositiveIntegerField(blank=True, null=True)),
                ("is_self_employed", models.BooleanField(default=False)),
                ("self_employment_hours_per_week", models.PositiveIntegerField(default=0)),
                ("self_employment_income_per_month", models.PositiveIntegerField(default=0)),
                ("is_managing_director", models.BooleanField(default=False)),
                ("is_startup_founder", models.BooleanField(default=False)),
                (
                    "has_employees",
                    models.BooleanField(default=False, help_text="Hires employees, excluding minijobbers"),
                ),
                (
                    "has_multiple_minijob_employees",
                    models.BooleanField(default=False, help_text="Hires MORE THAN ONE minijobber"),
                ),
            ],
            options={
                "verbose_name": "Health insurance signup",
                "ordering": ["-creation_date"],
            },
        ),
        migrations.AlterField(
            model_name="case",
            name="email",
            field=models.EmailField(blank=True, max_length=254, validators=[forms.utils.validate_email]),
        ),
        migrations.AlterField(
            model_name="case",
            name="referrer",
            field=models.CharField(blank=True),
        ),
    ]
