# Generated by Django 6.1 on 2026-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0018_healthinsurancesignup_alter_case_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthinsurancesignup",
            name="site",
            field=models.CharField(blank=True, default="allaboutberlin.com", max_length=100),
        ),
    ]
